import { Eye } from "lucide-react";
import TeamActivityDeviceStatus from "@/components/activity/TeamActivityDeviceStatus";
import TeamActivityStatusBadge from "@/components/activity/TeamActivityStatusBadge";
import AdminActivityEmptyState from "@/components/activity/AdminActivityEmptyState";
import { formatDuration, formatPercentage, formatRelativeTime } from "@/lib/activity/adminFormatters";
import { effectiveDeviceStatus } from "@/lib/activity/teamStatus";

export default function WorkforceActivityTable({ rows, filtered, nextCursor, loadingMore, onLoadMore, onSelect }) {
  if (!rows.length) return <section className="card p-5"><AdminActivityEmptyState title={filtered ? "No workforce records match" : "No monitored employees"} description={filtered ? "Reset or adjust loaded-page filters." : "Authorised workforce activity will appear after devices and tracking sessions exist."} /></section>;
  return <section className="card overflow-hidden"><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1300px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Employee</th><th className="p-4">Department</th><th className="p-4">Status</th><th className="p-4">Session</th><th className="p-4">Project / task</th><th className="p-4">Application</th><th className="p-4">Tracked / active / idle</th><th className="p-4">Offline</th><th className="p-4">Activity level</th><th className="p-4">Device / agent</th><th className="p-4">Last update</th><th className="p-4"></th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.employeeId}><td className="p-4 font-semibold">{row.employeeName}</td><td className="p-4 text-slate-500">{row.department || "Not provided"}</td><td className="p-4"><TeamActivityStatusBadge status={row.currentStatus} /></td><td className="p-4">{row.activeSessionId ? "Active" : "None"}</td><td className="p-4 text-slate-500">Not provided</td><td className="max-w-44 truncate p-4">{row.activeApplication || "Not collected"}</td><td className="p-4 text-xs">{formatDuration(row.trackedSecondsToday)} / {formatDuration(row.activeSecondsToday)} / {formatDuration(row.idleSecondsToday)}</td><td className="p-4 text-slate-500">Not provided</td><td className="p-4 font-semibold">{formatPercentage(row.activityPercentage)}</td><td className="p-4"><TeamActivityDeviceStatus status={effectiveDeviceStatus(row)} lastSeenAt={row.lastSeenAt} /><p className="mt-1 text-xs text-slate-500">{row.agentVersion || "Agent unavailable"}</p></td><td className="p-4 text-slate-500">{formatRelativeTime(row.lastSeenAt)}</td><td className="p-4"><button type="button" onClick={() => onSelect(row)} className="btn-secondary px-3"><Eye className="h-4 w-4" />View</button></td></tr>)}</tbody></table></div>
    <div className="divide-y divide-slate-100 lg:hidden">{rows.map(row => <article className="p-5" key={row.employeeId}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{row.employeeName}</h3><p className="text-sm text-slate-500">{row.department || "Department unavailable"}</p><div className="mt-2"><TeamActivityStatusBadge status={row.currentStatus} /></div></div><button aria-label={`View ${row.employeeName}`} type="button" onClick={() => onSelect(row)} className="icon-button h-10 w-10"><Eye className="h-4 w-4" /></button></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Tracked</dt><dd className="font-semibold">{formatDuration(row.trackedSecondsToday)}</dd></div><div><dt className="text-xs text-slate-500">Activity level</dt><dd className="font-semibold">{formatPercentage(row.activityPercentage)}</dd></div><div><dt className="text-xs text-slate-500">Device</dt><dd><TeamActivityDeviceStatus status={effectiveDeviceStatus(row)} lastSeenAt={row.lastSeenAt} /></dd></div><div><dt className="text-xs text-slate-500">Agent</dt><dd>{row.agentVersion || "Unavailable"}</dd></div></dl></article>)}</div>
    {nextCursor && <div className="border-t p-4 text-center"><button type="button" disabled={loadingMore} onClick={onLoadMore} className="btn-secondary">{loadingMore ? "Loading…" : "Load more workforce records"}</button></div>}
  </section>;
}
