"use client";
import { useParams } from "next/navigation";
import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, MapPinned, Plus, UsersRound } from "lucide-react";
import RoleShell from "@/components/RoleShell";
import LiveTeamMap from "@/components/LiveTeamMap";
import LocationSharing from "@/components/LocationSharing";
import { employees, expenses, tasks } from "@/lib/data";

const validRoles = ["employee", "manager", "admin"];
const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

function PageTitle({ title, subtitle, action }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{action}</div>; }
function Stat({ label, value, icon: Icon, tone = "text-blue-600 bg-blue-50" }) { return <div className="card p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span></div></div>; }
function Tasks({ editable = false }) { const [items, setItems] = useState(tasks); const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const add = () => { if (!title.trim()) return; setItems(x => [{ id: Date.now(), title, employee: "Aarav Sharma", client: "New client", address: "To be confirmed", status: "Assigned", priority: "Medium", time: "Today" }, ...x]); setTitle(""); setOpen(false); }; return <><PageTitle title={editable ? "Task board" : "My tasks"} subtitle="Track field work and its current progress." action={editable && <button onClick={() => setOpen(true)} className="btn-primary"><Plus className="h-4 w-4" />Assign task</button>} />{open && <div className="mb-5 card p-4"><label className="label">Task title</label><div className="flex gap-2"><input className="input" value={title} onChange={e => setTitle(e.target.value)} placeholder="Enter task title" /><button className="btn-primary" onClick={add}>Create</button></div></div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(task => <article key={task.id} className="card p-5"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{task.status}</span><span className="text-xs font-bold text-slate-500">{task.priority}</span></div><h2 className="mt-4 font-bold">{task.title}</h2><p className="mt-1 text-sm text-slate-500">{task.client} · {task.address}</p><div className="mt-5 flex items-center justify-between border-t pt-4 text-xs text-slate-500"><span>{task.employee}</span><span>{task.time}</span></div></article>)}</div></>; }
function Dashboard({ role }) { if (role === "employee") return <><PageTitle title="Good morning, Aarav" subtitle="Here is your field-work summary for today." /><div className="grid gap-4 md:grid-cols-3"><Stat label="Today's tasks" value="3" icon={Clock3} /><Stat label="Completed" value="1" icon={CheckCircle2} tone="text-emerald-600 bg-emerald-50" /><Stat label="Current status" value="On duty" icon={MapPinned} tone="text-violet-600 bg-violet-50" /></div><div className="mt-7"><LocationSharing /></div><div className="mt-7"><Tasks /></div></>; if (role === "manager") return <><PageTitle title="Operations overview" subtitle="A live view of your field team today." /><div className="grid gap-4 md:grid-cols-4"><Stat label="On duty" value="3" icon={UsersRound} /><Stat label="In progress" value="2" icon={Clock3} tone="text-amber-600 bg-amber-50" /><Stat label="Completed" value="1" icon={CheckCircle2} tone="text-emerald-600 bg-emerald-50" /><Stat label="Blocked" value="1" icon={AlertTriangle} tone="text-rose-600 bg-rose-50" /></div><div className="mt-7"><Tasks editable /></div></>; return <><PageTitle title="Admin overview" subtitle="Manage your FieldFlow workspace." /><div className="grid gap-4 md:grid-cols-4"><Stat label="Employees" value={employees.length} icon={UsersRound} /><Stat label="Active tasks" value="4" icon={Clock3} tone="text-violet-600 bg-violet-50" /><Stat label="Pending expenses" value={money(680)} icon={AlertTriangle} tone="text-amber-600 bg-amber-50" /><Stat label="Locations shared" value="3" icon={MapPinned} tone="text-emerald-600 bg-emerald-50" /></div></>; }
function Table({ title, rows, headers }) { return <><PageTitle title={title} subtitle={`Manage ${title.toLowerCase()} in your workspace.`} /><div className="card overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map(x => <th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-b last:border-0">{row.map((cell, j) => <td key={j} className="px-5 py-4 text-slate-700">{cell}</td>)}</tr>)}</tbody></table></div></>; }
export default function RolePage() { const { role, section = [] } = useParams(); const slug = section[0] || ""; const safeRole = validRoles.includes(role) ? role : "employee"; const content = useMemo(() => { if (!slug) return <Dashboard role={safeRole} />; if (slug === "tasks") return <Tasks editable={safeRole === "manager"} />; if (slug === "employees") return <Table title="Employees" headers={["Name", "Department", "Duty", "Tasks", "Performance"]} rows={employees.map(x => [x.name, x.department, x.duty, x.tasks, `${x.performance}%`])} />; if (slug === "expenses") return <Table title="Expenses" headers={["Employee", "Type", "Amount", "Status"]} rows={expenses.map(x => [x.employee, x.type, money(x.amount), x.status])} />; if (slug === "attendance") return <Table title="Attendance" headers={["Employee", "Check in", "Check out", "Hours", "Status"]} rows={employees.map((x, i) => [x.name, `0${8 + i}:5${i}`, i < 3 ? "18:15" : "—", i < 3 ? "8.5" : "—", i < 3 ? "Present" : "On duty"])} />; if (slug === "map") return <><PageTitle title="Live team map" subtitle="Locations update only while employees actively share them." /><LiveTeamMap /></>; if (slug === "reports") return <Table title="Daily reports" headers={["Employee", "Task", "Hours", "Status"]} rows={tasks.slice(0, 4).map((x, i) => [x.employee, x.title, `${5 + i}.0`, i % 2 ? "Submitted" : "Approved"])} />; return <PageTitle title={slug.replaceAll("-", " ")} subtitle="This FieldFlow module is ready for your data connection." />; }, [slug, safeRole]); return <RoleShell role={safeRole}>{content}</RoleShell>; }
